version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: "./docker/backend/Dockerfile"
    container_name: api
    hostname: api
    ports:
      - "8000:8000"
    networks:
      - app
    tty: true
    depends_on:
      - db
  db:
    build: 
      context: ./docker/mysql
      dockerfile: "Dockerfile"
    container_name: db
    hostname: db
    ports:
      - "3306:3306"
    networks:
      - app 
  # ui:
  #   build:
  #     context: .
  #     dockerfile: ./docker/frontend/Dockerfile
  #   container_name: ui
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app
networks:
  app:
    driver: 'bridge'      
